# Site settings
title:
header-img: img/home-bgg.jpg
email: krishnaqmar@gmail.com
copyright_name: redfruit
description:
baseurl: ""
url: "http://yourdomain.com"
twitter_username: mhfruit
github_username:  redfruitt
facebook_username:  RedFruitT
email_username:  krishnaqmar@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
